#!/bin/bash

export PATH=/bin:/sbin:$PATH

mknod /dev/mem c 1 1
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
mknod /dev/kmsg c 1 11

mknod /dev/initrd b 1 250

mknod /dev/sr0 b 11 0

mknod /dev/tty c 5 0

mknod /dev/sda b 8 0
mknod /dev/sda1 b 8 1
mknod /dev/sda2 b 8 2
mknod /dev/sda3 b 8 3

chmod 0660 /dev/*
chown -R 0:0 /*

mount -t proc /proc proc/
mount --rbind /sys sys/

bash
