#!/bin/bash

export PATH=/bin:/sbin:$PATH

mknod /dev/mem c 1 1
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9
mknod /dev/kmsg c 1 11

mknod /dev/initrd b 1 250

mknod /dev/hda b 3 0

mknod /dev/tty c 5 0

mknod /dev/sda b 8 0

bash
